# fly.toml app configuration file generated for plot on 2023-11-11T15:33:44-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plot"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
